env:
  browser: true
  es2023: true
  'vue/setup-compiler-macros': true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 14
plugins:
  - vue
  - '@typescript-eslint'
  - 'prettier'
rules:
  'vue/html-self-closing': 'off'
  'vue/max-attributes-per-line':
    - 'error'
    - singleline: 1
      multiline:
        max: 1
        allowFirstLine: false
  'vue/html-closing-bracket-newline':
    - 'error'
    - multiline: 'never'
  'vue/script-indent':
    - 'error'
    - 2
    - baseIndent: 2
  'arrow-parens':
    - 'error'
    - 'always'
root: true
